### ISSUE TITLE
設定ファイルを持たないように

### ISSUE THREAD

**Issue by otofune** [misskey-delta/misskey-docker#1]
ビルド時に必要なWebの設定は https://github.com/misskey-delta/misskey-web/blob/master/.ci/web.json を使えば解決する

**Comment by atnanasi** [comment]
実行時はホスト側から指定する感じ？

**Comment by rokoucha** [comment]
ビルド時に必要なWebの設定はそれを使っても解決出来なかったので https://github.com/misskey-delta/misskey-docker/issues/3 をするようにした
