### ISSUE TITLE
misskey-genを使いコンテナビルド後に設定を作るように

### ISSUE THREAD

**Issue by otofune** [misskey-delta/misskey-docker#3]
#2 のため。柔軟性が上がるのでは。

**Comment by rokoucha** [comment]
設定ファイルはコンテナの中に置くんすか？それともホストに？

**Comment by otofune** [comment]
設定ファイルは中かなあと思ってますね。生成方法はコンテナ内でgenを起動させたあとに実行するか、環境変数として定義などさせて自動で作るようにするとか。よくはわからないです

**Comment by rokoucha** [comment]
docker buildの時に--build-argで値を渡すと良さそうなのでそのようにする

**Comment by rokoucha** [comment]
https://github.com/misskey-delta/misskey-gen/issues/7 が終わらないと厳しいなどがある

**Comment by rokoucha** [comment]
https://github.com/misskey-delta/misskey-docker/commit/47a4993009ec09cadf16dff6a05b6d00e89076b8
